name: 'customer_churn'
version: '1.0.0'
config-version: 2

profile: 'customer_churn'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  customer_churn:
    staging:
      +materialized: view
      +schema: staging
      
    intermediate:
      +materialized: view
      +schema: intermediate
      
    marts:
      +materialized: table
      +schema: marts

seeds:
  customer_churn:
    +schema: raw