version: 2

models:
  - name: stg_customers
    description: "Cleaned raw data"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      
      - name: tenure_months
        tests:
          - not_null