version: 2

models:
  - name: fct_customer_churn
    description: "Final ML dataset"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      
      - name: Churn Label
        quote: true
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      
      - name: Tenure Months
        quote: true
        tests:
          - not_null
      
      - name: Monthly Charges
        quote: true
        tests:
          - not_null